### ISSUE TITLE
AddressSanitizer: invalid write at avc_ext.c:2456

### ISSUE THREAD

**Issue by HongxuChen** [gpac/gpac#1099]
POCs:
https://github.com/ntu-sec/pocs/blob/master/gpac-bceb03f/crashes/write_avc_ext.c%3A2456_1.mp4
https://github.com/ntu-sec/pocs/blob/master/gpac-bceb03f/crashes/write_avc_ext.c%3A2456_2.mp4

asan output:
```
[33m[iso file] Unknown box type 
[0m[33m[iso file] Unknown box type 
[0m[33m[iso file] Unknown box type sAsd
[0m[31m[iso file] Read Box type  (0x00000000) has size 0 but is not at root/file level, skipping
[0m[33m[iso file] Box "stbl" is invalid in container dref
[0m[33m[iso file] Unknown box type ...>
[0m[33m[iso file] Box "oinf" size 522 invalid (read 4580)
[0m[33m[iso file] Box "oinf" is invalid in container dref
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Box "dinf" size 36 invalid (read 4644)
[0m[31m[iso file] Missing DataInformationBox
[0m[33m[iso file] Unknown box type ...>
[0m[33m[iso file] Box "oinf" size 522 invalid (read 4580)
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Box "UNKN" is larger than container box
[0m[33m[iso file] Box "hinf" size 52 invalid (read 5412)
[0m[33m[iso file] Unknown box type sAsd
[0m[31m[iso file] Read Box type  (0x00000000) has size 0 but is not at root/file level, skipping
[0m[33m[iso file] Box "stbl" is invalid in container dref
[0m[33m[iso file] Unknown box type ...>
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
...
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[31m[BS] Attempt to overread bitstream
[0m[33m[iso file] Box "oinf" size 522 invalid (read 8343)
[0m[33m[iso file] Box "oinf" is invalid in container dref
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Box "dinf" size 36 invalid (read 4644)
[0m[31m[iso file] Incomplete box dinf
[0m[31m[iso file] Incomplete file while reading for dump - aborting parsing
[0m[33m[iso file] Unknown box type 
[0m[33m[iso file] Unknown box type 
[0m[33m[iso file] Unknown box type sAsd
[0m[31m[iso file] Read Box type  (0x00000000) has size 0 but is not at root/file level, skipping
[0m[33m[iso file] Box "stbl" is invalid in container dref
[0m[33m[iso file] Unknown box type ...>
[0m[33m[iso file] Box "oinf" size 522 invalid (read 4580)
[0m[33m[iso file] Box "oinf" is invalid in container dref
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Box "dinf" size 36 invalid (read 4644)
[0m[31m[iso file] Missing DataInformationBox
[0m[33m[iso file] Unknown box type ...>
[0mAddressSanitizer:DEADLYSIGNAL
=================================================================
==2229==ERROR: AddressSanitizer: SEGV on unknown address 0x608000010000 (pc 0x7f76164afe62 bp 0x60800000ffa0 sp 0x7ffeebfd9c40 T0)
==2229==The signal is caused by a WRITE memory access.
    #0 0x7f76164afe61 in gf_isom_oinf_read_entry /home/hongxu/FOT/gpac-fuzz/src/isomedia/avc_ext.c:2456:4
    #1 0x7f7616563b8c in gf_isom_box_read /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:1349:9
    #2 0x7f7616563b8c in gf_isom_box_parse_ex /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:199
    #3 0x7f7616566d8a in gf_isom_box_array_read_ex /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:1241:7
    #4 0x7f76164c2ad2 in unkn_Read /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_code_base.c:755:7
    #5 0x7f7616563b8c in gf_isom_box_read /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:1349:9
    #6 0x7f7616563b8c in gf_isom_box_parse_ex /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:199
    #7 0x7f7616566d8a in gf_isom_box_array_read_ex /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:1241:7
    #8 0x7f7616563b8c in gf_isom_box_read /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:1349:9
    #9 0x7f7616563b8c in gf_isom_box_parse_ex /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:199
    #10 0x7f76165628ab in gf_isom_parse_root_box /home/hongxu/FOT/gpac-fuzz/src/isomedia/box_funcs.c:42:8
    #11 0x7f76165853a4 in gf_isom_parse_movie_boxes /home/hongxu/FOT/gpac-fuzz/src/isomedia/isom_intern.c:206:7
    #12 0x7f761658c049 in gf_isom_open_progressive /home/hongxu/FOT/gpac-fuzz/src/isomedia/isom_read.c:378:7
    #13 0x52cb2c in mp4boxMain /home/hongxu/FOT/gpac/applications/mp4box/main.c:4342:9
    #14 0x5326a1 in main /home/hongxu/FOT/gpac/applications/mp4box/main.c:5489:9
    #15 0x7f7615135b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #16 0x424989 in _start (/home/hongxu/FOT/gpac/install/bin/MP4Box+0x424989)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/hongxu/FOT/gpac-fuzz/src/isomedia/avc_ext.c:2456:4 in gf_isom_oinf_read_entry
==2229==ABORTING
```

**Comment by aureliendavid** [comment]
Hi, 

Thanks for all the reports (and for including the test files!). 

I've fixed a bunch of them so I'm only commenting on this one. 

I'll close the one I've fixed but feel free to reopen them if the issue is still present. 

cheers

**Comment by HongxuChen** [comment]
Hi @aureliendavid , I had a quick check and found that on my machines these issues (from #1091 to #1099) still happen; one difference is that the assertion failure on #1093 has changed to a "read on NULL pointer deference".

```
$ MP4Box -v
MP4Box - GPAC version 0.7.2-DEV-rev570-g59ee23f4f-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: --prefix=/home/hongxu/FOT/gpac/install --cc=clang --cxx=clang++ --enable-debug --extra-ldflags=-fsanitize=address
Features: GPAC_64_BITS GPAC_HAS_SSL
```

**Comment by aureliendavid** [comment]
Is that with the same files as before? I could reproduce all of them before but none of them now. 

What's your OS / compiler version / ASAN version? Can you maybe try with gcc instead of clang? (I tried both with same result on my end). 

Are you using any ASAN_OPTIONS when running the tests? 

thanks

**Comment by HongxuChen** [comment]
Sorry I made a mistake -- I was linking the wrong library.
