### ISSUE TITLE
divide by zero at player startup in audio_render.c (non-deterministic, the input stream has no audio)

### ISSUE THREAD

**Issue by Ace17** [gpac/gpac#1136]
To reproduce:

```
./configure \
--extra-cflags="-fsanitize=address,undefined" \
--extra-ldflags="-fsanitize=address,undefined -ldl"

make

# generate divide_by_zero.mp4 (embedded here as bzip/base64)
echo "QlpoOTFBWSZTWcXgKagAAFr/////////////////////////////////////////////4AnfAB6rV5d7u57nXnu8MTXdzVpezbbtux1b74akqek9Jk0aegAg00MNRhNGjIyY1BowmQaDCBpk8oaZBppkyG0TINGmjJmoYBGhoA00YjTamI9TBNHqYaZJkyaepk00Ygwmmg1KVNjVP1JvST8lD0yh+hT1Pap6m2o1Nkn6JPamoeKM0JjRHpjUn6p6npskTaZGU9TamJvVH6aBT2TU09CaYmFP0xFNh6lP0m1HlGT1T9QRjT1T1Now1HqnqYnpNPFMniah4oBqUTTSaeJMh6T0jQ0xAyPUek0xMRp6gDE2UZM0mmTNE9TE9TJo9T1D0mRkND1DRoyNommmTIaYmRoPUyeoMjT1NAaDIAZMIGJtQyGgDUoyKYNQ9EaeppiNPTQnoNTE9NJ5NqJp6mymmjQBpoyaDR6R6mjBBiBkPUGgGQ0ANDTQDE0ANHqDINA00YQ00aANNGmTRoPUMinoj0CZMAAAAAAATAE0wAAAAAAABMJgCMAAAAAAAAAjAEyYTAaAAATEekCUSIJtI9SejSNMTKejTU9NIzTJo1PSZPSDRk9Qfqh6ENqGNQwm0TRkM1DBAekDwoyNGanpPUaM1HqGmg2kaepoeoyPU0egjI0aNB6mTTTRsppkls3RHfdemLHloaEyxFUB0RlCCZYcM2OxucKgaPbWnFEqBSMhvmhoTNODRFyIQx3rXbyLAQxSkFwgtDSoA/FIIYAYIjGlGINjtl2Oh5Gz/dNHISs5Rukw2hLHekeQnosdj1GEkKZ0aHOkmCVgkW5njfRRo+Sy855GnQb7piMVAFYwGKho3AYkXQ81h32IV+PrwtxATBk2OoSiPREjVBO7cYIkUoF0qNKiAkWKglOV57RhCfHhubaQ0k5T6nnsLnYCSAoJCUJ9UkVsaTG2NiPERBwQXEwGCqiIg5AJgaG1ERVFVFUFVACkVA5CoI/ezwDQPVQUUwpYMGxtmMXaqQV1iiAxPYYiDCxZmlaRRNKLWt/0NBjUxxSPwG0UVCjRjFVFHWR6jFQVUz61DTBVhjwYQZdhHPZ0WsbO8Q2v1dkg3UqTdxFDRGqASy8m7iDxroRUCkVDrMxqMrksedFguNkBCQgji4s8cJV1i6lcg2OIpGQHzT05g4b05Y/k73ygZ4mLMveDF2ChQnNnQF61pLvSmMultGn3ZCa2NNibmIYjexhXFGwjS/sMvFcXDXYJjvsOTwcMaQHH44bPmh8KEJYGdU26nLZFhBBEEomTX0rKMNRpmYJva12KmsNb7guEikulqyq2ESXnfO31+JPTI5uy8MCTpNJ/w68LMQbmJNTBKziKif7SwuhoIi7XjnsAk8KHvQpYO9aJfbN4LtSoaLC83i9MPM4XpK/Mmu1mZqoaR3vTA4IbipSfNR+OT7Ov0UHdbPIXbdXVbYP+fMPk4Y2oX23/2lBkyX46a2C33WN7abNnUFEzcIuIVwaF9ISHubGRtBIUhMCAuFH5FBGUBTX5nJgsGbhpCzuvqc9O6u1N3cBrJSUuvLfGIAIqaTXU2+Lgoy3COQtdGvah/knUPiVCei0QZBUAoCGAUBDbowXM2J5Ofp6tIYDtRejQ1jgWgMyNcjmwaR0iZM0edElpgsvXzOQs5PlSjxaoVyDOgwSyd3NPTo5vfdHUYlAWxIyjjZYFKCxfnGqQfqVCHzN16Xa0uep2eF4z0YFZO1ZG5QkUubf1fE76fuGVyykMQsVZX4yvYb5/hW7OdpxnB6NWFtfyLfIUCoJJEPkPEw0DEi9uYj54ioklGx88HwJA/7PYIjQjxhI4q0MIxQQS6USJWWsn4ciB8RkRksFqoyXutlvLWhMA4Gl6lCLr+oBYq1reokg6joJNr9NS+s7bHM5DpC0kguZSTNE57JqGIjklWSrKV/jgyqhEpGYiPV8jjQVmnhiiJCdwiAlY8VWKVWRm4EKuvm8XTPLOtlTHd0skajGy31JTYIrXq0EhkFgu3QrlVbCj/WqeI9rs6qKLU/T5Xm90Fkh2eCjY0S5BcpxE8HXQuQ0fWrLWgiTPA4/xG5x+ET9JopTYkiR7Zq1+uOPMImm67BcetzFroENfcyiWRb+mh9J5Rif4ZWU8A0/6jhSbd/ezqK2cWUlP5Jgk0H3AVWGYmOHlYYmCNuYWuViv2E2FtsK0iQ5GTWwh05dnCw+IotMIG8JsstClgYQoslKqvl5KfbkyAc8FBkMxsSTrFcNP7MXX5sxFYBl4cTEIrTLOzRwqA6Rw9pKMejqzWaa6alE2pvgmotc6evNyNvUmpW4QztS8Nta/HCLL1PB6iLOsb3k9m7LosyyoamwEF3YH+VE0DuQ2hQfZoEvTD5tuKwGcyYR/yZUowN8OWJSWZytf4xGqta+Lyj0ToqaEct3q8Ebr25US/e9NxIkQMd+OhdvQZB+vemplRJ+MWVhETx76uO77EkBBMMjjBm68Gts1KV7sJIUQzfffichOd+EvHKVfYSCjtrEYu99B2Ffg0dqvUBZGOGtkr/AUfc51/a5oW7tRa87q4UCiFCUp5tSw2la3NoDxXWIoJeMrrOydRrsIic6hbfPV2KuISC6KasRhKWcohvXkTDbTZO8P17ZwrSTN5bsKdZtUuxoDFm/SAKFeldi+cjtX8qTOANOMB/RDhxh4crb+J/JRZWbpqq41U8afi79o+wj7N9QoVN7RiXc9Xi+eRSdsKqG/a4/zy6elfoZG6fhXuukD73sM+mOsO3iV9WlY82k+l6J50ySEZcXw5ieNkWpnyTMjLVlLtjsMYvlQoSEpPTnUYKGkM28IawWH+wwEFkoxkB8NJ30qJYPrS/+54tj8iiC8JUkG6iHEhW0S0PQ6eHYcBbgW4IQaRDmQrvLv5E8sEta8h8WpRaxRHmY0NSGEfWtxCIEQ4XX8lwFPCB2NQAZnNnaC5h7RDEcTa5A9B/N3idES/NQg27bg3yc+6V1cElWanlFVrhPwLwSKR5T3w1Wp4aWtLgS9URMtR6KVBIbAaK+g/Dhbc0RKRb8ibvgTrYZswqaDHGRqUgJhx8WsGMOCcGgNM6YOSkCyhO302euKBAu9oKeA+7KYzwMDGABpkcyaf72qbqaJFYm1V5965GyMYhpz9TbVh68kgykbyZEtH5qV2LY9FHo/9QoD5rTJ+5xM52mPe73x9LgbPibr45XPm2NbT7zq72ZeWtDpiEEAmOmyz6YMb7Jm/WDoChVFz0TxC/EdNcayq+l2VcwfQt/zWuu8uhKC0B0DVGhu282A5xkltl+xV1CiBVIciPL77SzofYtRB3xmAsLqMXNuNWtbTRZsos6RJpIstI/EgwExb1iYxotSnAm0KB8oKobap007yO4edkPK63oxDmqgVWQ/UavMOipyP2+NEZiigUUN/3NpL9pfrd+hJMCVxSOE9dRNPVxpWyDTxG0pESO1K3TlnVjt36S0cZ62SUSHpDvjWfpplv3U1Knz+icmazjxeGkh1tMR3bxielixztRF4x7QcSVn117nq+rtnGYN25Nlk8Fr/t3aC6Nkc1Mn8L63ymcuNJq7CWltefZr9pr74F7Vr8BBsMO4SiGsZ0PHc5vnl9LA7GDQ0qhyAojgvrDAXZZ9eU/A//SPA+bgAqOa5lwExlnINmEZLTcQzyKlQy5xG0Kb9Y3qzZaaL6uMMqu921JG/epjNuST1VHrpoJ7EPfaCntQpljQW6ZiZ+X3Hq/jH3ZaOMvBjEH3yJx5bEgOZiVgkCYSRWfo5raEqyVc8HH01G9taQ7fvnhzt71S8MUGH12WahKzwydH+vYCaq0KJIsz8Un5rQvX8mouhyTETqeP2cnoF5Tp3jQk8zQusuNDb6BockEZd+bTUjGaYDnNwUyd0snLfMqRIoB16Kqly7B01yKFSIh+cryg7YXHJB7k7Ag7qlBMV1i+bhgqjSRQrn4t8CUtr+X2brbmTRnh0M+uYHPEGquTK0JWJmBqbIJkR17EZvKhqnCiW0bUu/AUhcYVndLcrlQza6KX1BkJbEt2AqtxMQTz1Mw34ddvBqRLwjIUDQmCmc+8mP/8HYtnPbLLDw4TUEvUfUIxEPhJxN+9pCUQV+rMsB81ZlofBsO7scKJOoFmiiTuy+gtj+dzCY76koILTSWkCciWNP9pmrv1HS3s9XtcSG4QwYYWNg37Suky0MKo7SW454RKA/LQURHlcqCHdZ3z+zguooPTWPv3m3dGLbViF8T4ScctjAtFtGnWjkI2M9chhahpMHisezy5p8keUhWTk2UNfpQZLKxtomvWtmFIHs8qMVyuOle0ItJtkB3xVFBWy1h111L9Bqm5TCtQ4p+UaXhHhAj/SMGed+Lzg7Mk7Ur6KJhsC5yW1azPBYnoVh0icbbQOOPtdrioZR1EjSyC1T+CJG0IfG31jSqcWEq3XqTS0IOLdIdOIj1FNWUD5cbSA3NJMP1MG3NOM+zwHJY+Q9QILy9zcQ94r4zOoH6PVw6kQ+7GUj8jTvKei5z6OE2QXFfA8FGp9nFZ+QII8ckjmjcCL1UfW31ydzcIVFmE0ER2jV8PpBwnfd1fwzHXtuiaXCHNAtfPAjUOPhLNRtTnQ45oXmZtCLNVN/xcxEHYzfv+S09iY1U7ua+n2vxcj6HQT97MKqeDigqBft4DfT5InOXQaTAHq5dkI9mR1/tzy0RIATMQgxnOawbuUxcJ9uCUN7uiDWuJ2SFbcKHtV72HRj2Z9QHgobgRH48kSyv5G9yFYwwsGVB+zNBgrjDRDrqES7FE1yl9aeMPpE+f8A32GhC132MRVELEczmA221ORiwtDaTktUrP9at5AS9mo0wuqwXlr0WQxamT61zXd3Xj0Xiyu58xs2wIO+giHaCQH3z7ahLbOi5QpZ6wMZ+sEDwMcDJ27F6ijzwMwDg9sGtgrY2qsttfE1NxGTihkhDLj70i5WMdRC8GqMSNIp7F00YVZel/jp2eLjnauV0vjaW1rii7r7oP3WwYbGw4YByUgQFeA+BwoQGcs3qBHgMBUBe0IEAz/IARoRALcprr6wT+DAcA+P6KYCfKt8kKtv8S8SXGuvJMo+gXI4f2jVn/4u5IpwoSGLwFNQA=" | base64 -d | bunzip2 > divide_by_zero.mp4

LD_LIBRARY_PATH=./bin/gcc ./bin/gcc/MP4Client -logs all@info divide_by_zero.mp4 
```

Output (non-deterministic, also does a heap-buffer-overflow sometimes):
```
Using config file in /home/ace/.gpac directory
System info: 7956 MB RAM - 8 cores
Refreshing list of modules in directory /home/ace/source/gpac/bibin/bin/gcc...
[Core] Added module gm_aac_in.so.
[Core] Added module gm_alsa.so.
[Core] Added module gm_mpd_in.so.
[Core] Added module gm_laser_dec.so.
[Core] Added module gm_amr_in.so.
[Core] Added module gm_jack.so.
[Core] Added module gm_widgetman.so.
[Core] Added module gm_mpegts_in.so.
[Core] Added module gm_ffmpeg_in.so.
[Core] Added module gm_ismacryp.so.
[Core] Added module gm_isom_in.so.
[Core] Added module gm_ogg_xiph.so.
[Core] Added module gm_audio_filter.so.
[Core] Added module gm_odf_dec.so.
[Core] Added module gm_sdl_out.so.
[Core] Added module gm_vtt_in.so.
[Core] Added module gm_img_in.so.
[Core] Added module gm_validator.so.
[Core] Added module gm_rtp_in.so.
[Core] Added module gm_timedtext.so.
[Core] Added module gm_ft_font.so.
[Core] Added module gm_ac3_in.so.
[Core] Added module gm_raw_out.so.
[Core] Added module gm_oss_audio.so.
[Core] Added module gm_x11_out.so.
[Core] Added module gm_osd.so.
[Core] Added module gm_netctrl.so.
[Core] Added module gm_saf_in.so.
[Core] Added module gm_soft_raster.so.
[Core] Added module gm_pulseaudio.so.
[Core] Added module gm_dummy_in.so.
[Core] Added module gm_nvdec.so.
[Core] Added module gm_svg_in.so.
[Core] Added module gm_ctx_load.so.
[Core] Added module gm_atsc_in.so.
[Core] Added module gm_openhevc_dec.so.
[Core] Added module gm_mp3_in.so.
[Core] Added module gm_bifs_dec.so.
Loaded 38 modules from directory (null).
Modules Found : 38 
Loading GPAC Terminal
[Thread Compositor] Starting
[Thread Compositor] Started
[Thread Compositor] At 2 Entering thread proc - thread ID 0xec1fc700
[Core] Load module file gm_x11_out.so
[Core] Load module file gm_x11_out.so : DONE
[Core] Load module file gm_soft_raster.so
[Core] Load module file gm_soft_raster.so : DONE
[Core] Load module file gm_sdl_out.so
[Core] Load module file gm_sdl_out.so : DONE
[SDL] Audio output setup
[SDL] Audio output setup - SampleRate 44100 Nb Channels 2 - 46 ms delay
[Core] Load module file gm_ft_font.so
/home/ace/source/gpac/src/compositor/audio_render.c:413:83: runtime error: division by zero
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14876==ERROR: AddressSanitizer: FPE on unknown address 0x7f0bf50c6256 (pc 0x7f0bf50c6256 bp 0x7f0be6a1fd70 sp 0x7f0be6a1fc80 T4)
[Core] Load module file gm_ft_font.so : DONE
[Thread MediaManager] Starting
[X11] Hardware has no color keying
[X11] Using XV YUV Overlays
    #0 0x7f0bf50c6255 in gf_ar_fill_output /home/ace/source/gpac/src/compositor/audio_render.c:413
    #1 0x7f0beb59a021 in sdl_fill_audio /home/ace/source/gpac/modules/sdl_out/audio.c:50
    #2 0x7f0beb42b6e8  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x216e8)
    #3 0x7f0beb4725eb  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x685eb)
    #4 0x7f0beb4e3f68  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xd9f68)
    #5 0x7f0bf8796f29 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7f29)
    #6 0x7f0bf0d67ede in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xf7ede)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /home/ace/source/gpac/src/compositor/audio_render.c:413 in gf_ar_fill_output
Thread T4 (SDLAudioP1) created by T1 here:
    #0 0x7f0bf87f9ef0 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x49ef0)
    #1 0x7f0beb4e3fd2  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xd9fd2)

Thread T1 created by T0 here:
    #0 0x7f0bf87f9ef0 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x49ef0)
    #1 0x7f0bf3dd0040 in gf_th_run /home/ace/source/gpac/src/utils/os_thread.c:265
    #2 0x7f0bf50f1092 in gf_sc_new /home/ace/source/gpac/src/compositor/compositor.c:626
    #3 0x7f0bf5080e5a in gf_term_new /home/ace/source/gpac/src/terminal/terminal.c:698
    #4 0x559e0e2b1c96 in mp4client_main /home/ace/source/gpac/applications/mp4client/main.c:1617
    #5 0x559e0e2b6cdd in main /home/ace/source/gpac/applications/mp4client/main.c:2414
    #6 0x7f0bf0c92b16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

[Thread MediaManager] Started
==14876==ABORTING
[Thread MediaManager] At 217 Entering thread proc - thread ID 0xe5e33700
[Thread MediaManager] Couldn't set priority(2) for thread ID 0xe5e33700
[Thread MediaManager] Couldn't set priority(2) for thread ID 0xe5e33700
```

**Comment by Ace17** [comment]
I'm on GNU/Linux Debian Testing, 64 bits.

```
$ gcc --version
gcc (Debian 8.2.0-5) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
However, it's definitely timing-dependent. Maybe try to overload your CPU with some build at the same time, to randomize your timings?

**Comment by Ace17** [comment]
Here's a way to force the error to happen every time:

```
diff --git a/src/compositor/audio_render.c b/src/compositor/audio_render.c
index cc86354a3..9a325e890 100644
--- a/src/compositor/audio_render.c
+++ b/src/compositor/audio_render.c
@@ -304,20 +304,23 @@ static GF_Err gf_ar_setup_output_format(GF_AudioRenderer *ar)
                if (e) return e;
        }
        gf_mixer_set_config(ar->mixer, freq, nb_chan, nb_bits, in_cfg);
        ar->audio_delay = ar->audio_out->GetAudioDelay(ar->audio_out);
 
        ar->audio_out->SetVolume(ar->audio_out, ar->volume);
        ar->audio_out->SetPan(ar->audio_out, ar->pan);
 
        ar->time_at_last_config = ar->current_time;
        ar->bytes_requested = 0;
+
+       gf_sleep(1000);
+
        ar->bytes_per_second = freq * nb_chan * nb_bits / 8;
 
        if (ar->audio_listeners) {
                u32 k=0;
                GF_AudioListener *l;
                while ((l = (GF_AudioListener*)gf_list_enum(ar->audio_listeners, &k))) {
                        l->on_audio_reconfig(l->udta, in_freq, in_bps, in_ch, in_cfg);
                }
        }
        return GF_OK;

```

**Comment by jeanlf** [comment]
got it! Should now be fixed, could you check it?

**Comment by Ace17** [comment]
yep, can't reproduce it anymore. Thanks!
