### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow utils/bitstream.c:253 in BS_ReadByte

### ISSUE THREAD

**Issue by dr3dd589** [gpac/gpac#1425]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

System info:
Ubuntu 18.04.6 LTS, X64, gcc version 7.4.0, gpac (latest [master](https://github.com/gpac/gpac/commit/8c5e847185d74462d674ee7d28fb46c29dae6dd2))

Compile Command:

```asm
$ CC="gcc -fsanitize=address -g" CXX="g++ -fsanitize=address -g" ./configure --static-mp4box
$ make
```
Run Command:

```asm
./MP4Box -dash 1000 crash_4
```
ASAN info:

```asm
==3870==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000000084 at pc 0x5563f87acaa8 bp 0x7ffde8d66f50 sp 0x7ffde8d66f40
READ of size 1 at 0x603000000084 thread T0
    #0 0x5563f87acaa7 in BS_ReadByte utils/bitstream.c:253
    #1 0x5563f87acaa7 in gf_bs_read_bit utils/bitstream.c:287
    #2 0x5563f87acc7d in gf_bs_read_int utils/bitstream.c:319
    #3 0x5563f8ae9270 in gf_odf_read_cc_name odf/odf_code.c:1905
    #4 0x5563f8ad7fb2 in gf_odf_parse_descriptor odf/descriptors.c:159
    #5 0x5563f8ae17fe in gf_odf_read_iod odf/odf_code.c:505
    #6 0x5563f8ad7fb2 in gf_odf_parse_descriptor odf/descriptors.c:159
    #7 0x5563f8c2ac7d in gf_m2ts_process_pmt media_tools/mpegts.c:2196
    #8 0x5563f8c1d58b in gf_m2ts_section_complete media_tools/mpegts.c:1619
    #9 0x5563f8c1e013 in gf_m2ts_gather_section media_tools/mpegts.c:1749
    #10 0x5563f8c2483e in gf_m2ts_process_packet media_tools/mpegts.c:3489
    #11 0x5563f8c2483e in gf_m2ts_process_data media_tools/mpegts.c:3550
    #12 0x5563f8c341f6 in gf_m2ts_probe_file media_tools/mpegts.c:4689
    #13 0x5563f8b5bb10 in gf_dash_segmenter_probe_input media_tools/dash_segmenter.c:5505
    #14 0x5563f8b8282a in gf_dasher_add_input media_tools/dash_segmenter.c:6669
    #15 0x5563f875dcce in mp4boxMain /home/dr3dd/fuzzing/gpac/applications/mp4box/main.c:4705
    #16 0x7fe2f4e87b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #17 0x5563f874c9a9 in _start (/home/dr3dd/fuzzing/gpac/bin/gcc/MP4Box+0x1659a9)

0x603000000084 is located 0 bytes to the right of 20-byte region [0x603000000070,0x603000000084)
allocated by thread T0 here:
    #0 0x7fe2f5b0fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x5563f8c1cd38 in gf_m2ts_section_complete media_tools/mpegts.c:1559

SUMMARY: AddressSanitizer: heap-buffer-overflow utils/bitstream.c:253 in BS_ReadByte
Shadow bytes around the buggy address:
  0x0c067fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff8000: fa fa 00 00 04 fa fa fa 00 00 07 fa fa fa 00 00
=>0x0c067fff8010:[04]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3870==ABORTING
```
here is crash file:
[crash_4.zip](https://github.com/gpac/gpac/files/4302450/crash_4.zip)

**Comment by jeanlf** [comment]
fixed, thanks for the report
