### ISSUE TITLE
[Filters] Crash while transcoding aac to vorbis

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1468]
Hi, I encountered a crash while trying the transcoding pipeline with the filters branch.

Here is the command:

```
gpac  -i sound.aac enc:c=vorbis @ -o test.ogg
gpac: filters/ff_enc.c:590: ffenc_audio_append_samples: Assertion `ctx->samples_in_audio_buffer + nb_samples <= (u32) ctx->encoder->frame_size' failed.
Abandon (core dumped)
```

Here is the stack trace:
```
#0  0x00007ffff7397ce5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7381857 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7381727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff7390426 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007ffff7b5c4bd in ffenc_audio_append_samples (ctx=0x5555555c1b30, 
    data=0x555555685f50 "t\377\v\274T\377\253\273_\377 <o\377\020\274F\377\271\273P\377/<b\177\236\274\030\377\347\274d\377\233\272\017\377\360\273\060\377O\273{\377\204<\006\177z\274j\177\026\275_?\241\274\"\377ݼ%\277ڼ \377_\273\006\377y\273w\377\b\274#\377ܻY\377\246\273,\377\323;\\\377\243;)\377\326;0\277\317<]\377\242<\026\177i<&\177\332<s\277\214<)\377V<\006\177\372<\030\177\347<\b\177w<>\177A<3\377L<b\277\235<\003\277\374<T?,=E?;=g\377\030=>\277\301<~\377\001<~\177\001\274^\177\"\274K\377\064<M\277\262<@\377\277:4\377˺\"\377\335;"..., size=8192, sample_offset=64, nb_samples=960) at filters/ff_enc.c:590
#5  0x00007ffff7b5cf63 in ffenc_process_audio (filter=0x5555555c0fe0, ctx=0x5555555c1b30) at filters/ff_enc.c:721
#6  0x00007ffff7b5d3ba in ffenc_process (filter=0x5555555c0fe0) at filters/ff_enc.c:800
#7  0x00007ffff7ae1314 in gf_filter_process_task (task=0x5555555bd1f0) at filter_core/filter.c:2072
#8  0x00007ffff7ad3687 in gf_fs_thread_proc (sess_thread=0x5555555a8df0) at filter_core/filter_session.c:1432
#9  0x00007ffff7ad3fe3 in gf_fs_run (fsess=0x5555555a8d60) at filter_core/filter_session.c:1669
#10 0x000055555555df8b in gpac_main (argc=7, argv=0x7fffffffdc78) at main.c:1953
#11 0x000055555555e25d in main (argc=7, argv=0x7fffffffdc78) at main.c:2008
```

Here is the aac file: https://www.mediafire.com/file/rfix2uay3xdrjh5/sound.aac/file

Note: transcoding aac -> aac and aac -> mp3 works, so it doesn't seem to be related to the input
Note: executed from a66b6eeeffc18f3ed9913369c2fff5882b20a48f compiled in debug

-----------------------------
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
this should now be fixed, thanks for the report
