### ISSUE TITLE
Possible Bug - Segmentation fault found

### ISSUE THREAD

**Issue by lyonnhk** [gpac/gpac#2146]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Version: 
```
MP4Box -version
MP4Box - GPAC version 2.1-DEV-rev48-gf6d6225a9-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io/
 MINI build (encoders, decoders, audio and video output disabled)

Please cite our work in your research:
 GPAC Filters: https://doi.org/10.1145/3339825.3394929
 GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: --static-bin
Features: GPAC_CONFIG_LINUX GPAC_64_BITS GPAC_HAS_SOCK_UN GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_OPENSVC  GPAC_DISABLE_3D
```

Command:
`MP4Box -lsr poc1`

[poc1.zip](https://github.com/gpac/gpac/files/8274174/poc1.zip)

Result:
`Segmentation fault`

bt:
```
[iso file] Unknown box type FF00ak in parent moov
[iso file] Unknown box type t0E18 in parent trak
[iso file] extra box maxr found in hinf, deleting
[iso file] Unknown box type 80rak in parent moov
[iso file] Incomplete box mdat - start 11495 size 803729
[iso file] Incomplete file while reading for dump - aborting parsing
[iso file] Unknown box type FF00ak in parent moov
[iso file] Unknown box type t0E18 in parent trak
[iso file] extra box maxr found in hinf, deleting
[iso file] Unknown box type 80rak in parent moov
[iso file] Incomplete box mdat - start 11495 size 803729
[iso file] Incomplete file while reading for dump - aborting parsing
MPEG-4 BIFS Scene Parsing
[ODF] Reading bifs config: shift in sizes (not supported)
[BIFS] Node Group not allowed as field/child of NDT type 37
Scene loaded - dumping 1 systems streams           

Program received signal SIGSEGV, Segmentation fault.
gf_dump_vrml_simple_field (sdump=sdump@entry=0x5555558873e0, parent=<optimized out>, field=...) at scene_manager/scene_dump.c:759
759			gf_dump_vrml_node(sdump, *(GF_Node **)field.far_ptr, 0, NULL);

   0x00007ffff71d1e1a <+346>:	add    %rbp,%r8
   0x00007ffff71d1e1d <+349>:	movzbl (%r8),%eax
   0x00007ffff71d1e21 <+353>:	add    $0x1,%al
   0x00007ffff71d1e23 <+355>:	jb     0x7ffff71d23b5 <gf_dump_vrml_simple_field+1781>
   0x00007ffff71d1e29 <+361>:	add    %r14d,%eax
   0x00007ffff71d1e2c <+364>:	xor    %ecx,%ecx
   0x00007ffff71d1e2e <+366>:	xor    %edx,%edx
   0x00007ffff71d1e30 <+368>:	mov    %r12,%rdi
   0x00007ffff71d1e33 <+371>:	mov    %al,(%r8)
   0x00007ffff71d1e36 <+374>:	movl   $0x516d,%fs:(%rbx)
=> 0x00007ffff71d1e3d <+381>:	mov    0x0(%r13),%rsi
   0x00007ffff71d1e41 <+385>:	callq  0x7ffff71cd170 <gf_dump_vrml_node>
   0x00007ffff71d1e46 <+390>:	mov    %fs:(%rbx),%r8d
   0x00007ffff71d1e4a <+394>:	xor    $0x2a76,%r8d
   0x00007ffff71d1e51 <+401>:	add    %rbp,%r8
   0x00007ffff71d1e54 <+404>:	xor    %r12d,%r12d
   0x00007ffff71d1e57 <+407>:	movzbl (%r8),%ebp
   0x00007ffff71d1e5b <+411>:	add    $0x1,%bpl
   0x00007ffff71d1e5f <+415>:	jb     0x7ffff71d237f <gf_dump_vrml_simple_field+1727>
   0x00007ffff71d1e65 <+421>:	add    %r12d,%ebp
   0x00007ffff71d1e68 <+424>:	mov    %bpl,(%r8)

Stack level 0, frame at 0x7fffffff6f30:
 rip = 0x7ffff71d1e3d in gf_dump_vrml_simple_field (scene_manager/scene_dump.c:759); saved rip = 0x7ffff71d27aa
 called by frame at 0x7fffffff6fc0
 source language c.
 Arglist at 0x7fffffff6eb8, args: sdump=sdump@entry=0x5555558873e0, parent=<optimized out>, field=...
 Locals at 0x7fffffff6eb8, Previous frame's sp is 0x7fffffff6f30
 Saved registers:
  rbx at 0x7fffffff6ef8, rbp at 0x7fffffff6f00, r12 at 0x7fffffff6f08, r13 at 0x7fffffff6f10, r14 at 0x7fffffff6f18, r15 at 0x7fffffff6f20, rip at 0x7fffffff6f28


(gdb) where
#0  gf_dump_vrml_simple_field (sdump=sdump@entry=0x5555558873e0, parent=<optimized out>, field=...) at scene_manager/scene_dump.c:759
#1  0x00007ffff71d27aa in DumpMultipleIndexedReplace (sdump=sdump@entry=0x5555558873e0, com=<optimized out>, com=<optimized out>) at scene_manager/scene_dump.c:1731
#2  0x00007ffff71c7ace in gf_sm_dump_command_list
    (sdump=sdump@entry=0x5555558873e0, comList=<optimized out>, indent=indent@entry=1, skip_first_replace=skip_first_replace@entry=GF_TRUE) at scene_manager/scene_dump.c:2958
#3  0x00007ffff71db286 in gf_sm_dump
    (ctx=ctx@entry=0x55555587e660, rad_name=rad_name@entry=0x555555832de0 <outfile> "poc1", is_final_name=is_final_name@entry=GF_FALSE, dump_mode=dump_mode@entry=GF_SM_DUMP_LASER) at scene_manager/scene_dump.c:3575
#4  0x00005555555b9e20 in dump_isom_scene
    (file=<optimized out>, inName=<optimized out>, is_final_name=<optimized out>, dump_mode=<optimized out>, do_log=<optimized out>, no_odf_conv=<optimized out>)
    at filedump.c:217
#5  0x000055555559ae41 in mp4boxMain (argc=<optimized out>, argv=<optimized out>) at main.c:6146
#6  0x00007ffff65d60b3 in __libc_start_main (main=
    0x55555556e920 <main>, argc=3, argv=0x7fffffffe068, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe058)
    at ../csu/libc-start.c:308
#7  0x000055555556eb2e in _start () at main.c:6601
```

**Comment by lyonnhk** [comment]
Hi @jeanlf , are you willing to help us to request a CVE ID through [GitHub Security Advisories](https://github.com/gpac/gpac/security/advisories) for this bug? Thanks for your help!

**Comment by risicle** [comment]
This should indeed have a CVE
