### ISSUE TITLE
Cannot load libgpac [on devices running Android 4.4.2 or earlier]

### ISSUE THREAD

**Issue by emmanouil** [gpac/gpac#596]
This happens because function "atof" is used (log from Android Monitor at the end). 
[Apparently](https://groups.google.com/forum/#!topic/android-ndk/RjO9WmG9pfE), when building for Android API > 19 by default some inline functions are not included since they are in "libc.so" (the Bionic C library used by Android).
However, we are building for API 18 (4.3.1), so I assume that that this is a new undocumented "feature" of the latest NDK (12b).
In order to be able to build, NDK r11c (or earlier) must be used.

Donwload link for NDK r11c (Linux): http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip

Donwload link for NDK r11c (OS X): http://dl.google.com/android/repository/android-ndk-r11c-darwin-x86_64.zip
  
  
P.S. Maybe we should update the documentation until it's fixed
  ---
  ---
  

Android Monitor Log:
```
07-26 16:16:33.231 15977-16059/? I/LibrariesLoader: Loading library gpacWrapper...
07-26 16:16:33.231 15977-16059/? D/dalvikvm: Trying to load lib /data/app-lib/com.gpac.Osmo4-1/libgpacWrapper.so 0x42a50648
07-26 16:16:33.231 15977-16059/? E/dalvikvm: dlopen("/data/app-lib/com.gpac.Osmo4-1/libgpacWrapper.so") failed: dlopen failed: could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
07-26 16:16:33.236 15977-16059/? E/LibrariesLoader: Failed to load library : gpacWrapper due to link error dlopen failed: could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
                                                    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
                                                        at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                        at java.lang.System.loadLibrary(System.java:526)
                                                        at com.gpac.Osmo4.GPACInstance.loadAllLibraries(GPACInstance.java:72)
                                                        at com.gpac.Osmo4.GPACInstance.<init>(GPACInstance.java:142)
                                                        at com.gpac.Osmo4.Osmo4Renderer.onSurfaceCreated(Osmo4Renderer.java:26)
                                                        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
                                                        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
07-26 16:16:33.286 15977-16059/? E/LibrariesLoader: Exceptions while loading libraries:
                                                    gpacWrapper[UnsatisfiedLinkError]: dlopen failed: could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
                                                    gm_droid_cam[UnsatisfiedLinkError]: dlopen failed: could not load library "libgpac.so" needed by "libgm_droid_cam.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
                                                    gm_droid_mpegv[UnsatisfiedLinkError]: dlopen failed: could not load library "libgpac.so" needed by "libgm_droid_mpegv.so"; caused by cannot locate symbol "atof" referenced by "libgpac.so"...
                                                    gpac[UnsatisfiedLinkError]: dlopen failed: cannot locate symbol "atof" referenced by "libgpac.so"...
```

**Comment by emmanouil** [comment]
[Android NDK Github Issue](https://github.com/android-ndk/ndk/issues/120)

**Comment by rbouqueau** [comment]
Is this still relevant?

**Comment by emmanouil** [comment]
I cannot test it now, but I assume that after the latest updates on Android it should be fixed. I am closing the issue for now and I will re-open it if there is still a problem
