### ISSUE TITLE
WRONG project libbluray failed on java.lang.UnsupportedClassVersionError major.minor version 52.0

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#836]
(Windows 10, 64bit)
Run git pull to update most recent files, media-autobuild_suite.bat script fails on the libbluray compilation.

**Java class versions** J2SE8 = 52, J2SE7 = 51 

I have the following folders but just JDK1.7 is installed and be visible in winregistry. JDK1.8 folder is unzipped without running setup.exe (zero-installation scheme).
C:\Program Files\Java\jdk1.7.0_75
C:\Program Files\Java\jdk1.8.0_112

**Winregistry**
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\
CurrentVersion=1.7
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\1.7
JavaHome=C:\Program Files\Java\jdk1.7.0_75
```

I suspect build scripts take JDK1.8 folder and libbluray fails or some of the compilations use JDK1.8 and some part JDK1.7 thus creating a mismatch in class version magic number.

Helper function `build/media-suite_helper.sh/get_java_home()` is looking for registry value so it should take JDK1.7 release. I cannot verify which version was taken, script is using echo command to print value somewhere but none of the logfiles has it.

Is this a common problem and ideas to solve this? I cannot move jdk1.8 folder anywhere else at the moment actually windows locks a folder cannot even rename it.

> 
> dvdnav git ................................................ [Up-to-date]
>   Running git update for libbluray...
> ┌ libbluray git ..................................... [Recently updated]
> ├ Running autoreconf...
> ├ Running ant-diagnostics...
> Likely error:
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
> Exception in thread "main" ant-diagnostics failed. Check C:/projects/media-autobuild_suite/media-autobuild_suite/build/libbluray-git/ab-suite.ant-diagnostics.log
> This is required for other packages, so this script will exit.
>   Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/69n.zip
> Copy and paste [logs.zip](https://0x0.st/69n.zip) in the GitHub issue.
> 
> CFLAGS: -mthreads -mtune=generic -O2 -pipe LDFLAGS: -pipe -static-libgcc -static-libstdc++ ant -diagnostics java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
`

**Comment by Murmur** [comment]
Oops, wrong copypaste tabsheet in a browser. Ignore this please.
